version: "3.9"
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: mysql:5.7.22
        ports:
            - 33306:3306
        environment:
            MYSQL_DATABASE: admin
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
